Update 2022-11-19-monitoring-with-uncertainty.md
saattrupdan/saattrupdan.github.io pull request #2
Opened 2022-11-21 08:36 UTC by cmougan

Python code snippet

2022-11-21 08:49 UTC, cmougan commented
Added a snippet of code and made some minimal changes :)

2022-11-22 10:43 UTC, cmougan commented
@saattrupdan perhaps in the preprint, in the comment, you can add: "AAAI'23 Safe and Robust AI track"

2022-11-22 11:55 UTC, saattrupdan commented
> @saattrupdan perhaps in the preprint, in the comment, you can add: "AAAI'23 Safe and Robust AI track"

Updated now - it'll take ~1-2 days for ArXiv to update, however.

2022-11-22 12:01 UTC, saattrupdan requested changes

2022-11-22 12:01 UTC, saattrupdan commented on _posts/2022-11-19-monitoring-with-uncertainty.md
> +#[ 0.01,  0.  , -0.  ]
Adding comments:

```suggestion
# Generate normal-distributed random data
x1 = np.random.normal(1, 0.1, size=10000)
x2 = np.random.normal(1, 0.1, size=10000)
x3 = np.random.normal(1, 0.1, size=10000)

# Create a synthetic dataset with the random data, of shape (1, 3)
X = np.array([x1, x2, x3]).T

# Create out-of-distribution data by shifting the first feature by 5
X_ood = np.array([x1 + 5, x2, x3]).T

# Create the target variable, which depends non-linearly on `x1`, linearly on `x2`, and does not depend on `x3` at all
y = x1 ** 2 + x2 + np.random.normal(0, 0.01, 10000)

# Create linear regression model with uncertainty estimation support, using our `Boot` wrapper class
clf = Boot(LinearRegression())

# Fit the model to the data
clf = clf.fit(X, y)

# Compute predictions along with prediction intervals on the out-of-distribution data
preds, intervals = clf.predict(X_ood, uncertainty=0.05)

# Compute the uncertainty, being the width of the prediction intervals
unc = intervals[:, 1] - intervals[:, 0]

# As for explaining where the uncertainty comes from, we fit a new linear regression model
# on the out-of-distribution data, which attempts to predict the uncertainties
m = LinearRegression().fit(X_ood, unc)

# Print out the coefficients of the second model, which corresponds to the SHAP values.
# We see that it puts no importance on any of the variables, as they are merely random
np.round(m.coef_, decimals=2)
#[ 0.01,  0.  , -0.  ]
```

2022-11-22 12:52 UTC, cmougan reviewed
Good idea to comment

2022-11-22 14:00 UTC, saattrupdan approved these changes
LGTM!

2022-11-22 14:00 UTC, merged